"use client";
import Image from "next/image";
import { BrandLoading } from "@/components/brand-loading";
import Link from "next/link";
import { useEffect, useRef, useState, type ReactNode } from "react";
import { Button } from "@/components/ui/button";
import { ChatBubble, ChatComposer, ChatShell } from "@/features/chat/chat-shell";
import { HomeFeedbackAction, type HomeFeedbackRoutine } from "@/features/home/home-feedback-action";
import { appendChatMessage, buildActiveTurnContext, canShowFinalizeButton, clearConversationSession, conversationStorageKey, createRestartedConversationState, openingMessage, parseConversationSession, type ChatMessage } from "@/features/skin-conversation/skin-conversation-state";
import { DAILY_STATE_AREAS, DAILY_STATE_CONCERN_KINDS, DAILY_STATE_DETAIL_FINDINGS, skinCheckinSchema, type DailyState, type DailyStateDetailFinding, type SkinCheckinInput } from "@/schemas/checkin";
import { skinConversationResultSchema, type SkinConversationResult } from "@/schemas/skin-conversation";
import type { Profile } from "@/schemas/profile";
import type { RecentSkinTrend } from "@/domain/recent-skin-trend";
import { getTodayNewChangeIndicators } from "@/features/skin-conversation/today-new-change-indicator";
import { buildTodayObservationSummary } from "@/features/skin-conversation/today-observation-summary";
import { conversationErrorCode, conversationErrorMessage, type ConversationApiErrorCode } from "@/features/skin-conversation/skin-conversation-api-error";

type Status = "idle" | "sending" | "streaming" | "saving" | "error" | "saved";
const labels: Record<DailyStateDetailFinding, string> = { oil_shine: "出油", dryness: "干燥", flaking: "起皮", roughness: "粗糙", redness: "泛红", small_bumps: "小凸起", blemishes: "痘痘", blackheads: "黑头", tightness: "紧绷", itching: "发痒", burning: "灼热", tenderness: "触痛", other: "其他" };

export function SkinConversation({ today, userId, profile = null, feedbackRoutines = [], isDevelopment = false, presentation = "default", topActions = null }: { today: string; userId: string; profile?: Pick<Profile, "skin_type" | "long_term_skin_baseline"> | null; recentTrends?: RecentSkinTrend[]; feedbackRoutines?: HomeFeedbackRoutine[]; isDevelopment?: boolean; presentation?: "default" | "home"; topActions?: ReactNode }) {
  const key = conversationStorageKey(userId, today);
  const [messages, setMessages] = useState<ChatMessage[]>([openingMessage]); const [composer, setComposer] = useState(""); const [proposal, setProposal] = useState<SkinConversationResult | null>(null); const [editor, setEditor] = useState<SkinCheckinInput | null>(null); const [status, setStatus] = useState<Status>("idle"); const [notice, setNotice] = useState(""); const [hydrated, setHydrated] = useState(false); const [unsaved, setUnsaved] = useState(false); const [savedState, setSavedState] = useState<DailyState | null>(null); const [completionConfirmationPending, setCompletionConfirmationPending] = useState(false); const [resettingTestRecord, setResettingTestRecord] = useState(false); const [retryMessage, setRetryMessage] = useState("");
  const sendInFlight = useRef(false);
  const saveInFlight = useRef(false);
  useEffect(() => { const saved = parseConversationSession(sessionStorage.getItem(key)); queueMicrotask(() => { if (saved) { setMessages(saved.messages.length ? saved.messages : [openingMessage]); setComposer(saved.composer); setProposal(saved.proposal); setEditor(saved.editor); setCompletionConfirmationPending(saved.completionConfirmationPending); setUnsaved(true); } setHydrated(true); }); }, [key]);
  useEffect(() => { if (hydrated && status !== "saved" && unsaved) sessionStorage.setItem(key, JSON.stringify({ messages, composer, proposal, editor, completionConfirmationPending })); }, [completionConfirmationPending, composer, editor, hydrated, key, messages, proposal, status, unsaved]);
  const append = (message: ChatMessage) => setMessages((current) => appendChatMessage(current, message));
  async function send(retry = false, finalize = false) { const message = finalize ? "请根据完整对话整理今天的皮肤状态。" : (retry ? retryMessage : composer).trim(); if (!hydrated || (!finalize && !message) || status === "sending" || status === "streaming" || status === "saving" || (!finalize && proposal) || sendInFlight.current === true) return; const clientStartedAt = performance.now(); sendInFlight.current = true; const active_turn_context = buildActiveTurnContext(messages); const messageId = crypto.randomUUID(); const replyId = `reply:${messageId}`; let streamedReply = ""; let pendingDelta = ""; let frame: number | null = null; let firstVisibleLogged = false; const flushReply = () => { if (frame !== null) { cancelAnimationFrame(frame); frame = null; } if (!pendingDelta) return; const delta = pendingDelta; pendingDelta = ""; streamedReply += delta; setMessages((current) => { const index = current.findIndex((item) => item.id === replyId); if (index < 0) return [...current, { id: replyId, role: "assistant", content: delta, kind: "reply" }]; const next = [...current]; next[index] = { ...next[index], content: next[index].content + delta }; return next; }); if (!firstVisibleLogged) { firstVisibleLogged = true; requestAnimationFrame(() => { if (process.env.NODE_ENV === "development") console.info("[skin-conversation]", { stage: "client_timing", transport: "sse", submit_to_first_visible_reply_ms: Math.round(performance.now() - clientStartedAt) }); }); } };
    const enqueueReplyDelta = (delta: string) => { pendingDelta += delta; if (frame === null) frame = requestAnimationFrame(flushReply); };
    setUnsaved(true); if (!retry && !finalize) append({ id: messageId, role: "user", content: message }); setComposer(""); setStatus("sending"); setNotice(""); try { const response = await fetch("/api/v1/skin-conversations", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ message, active_turn_context, recorded_date: today, completion_confirmation_pending: completionConfirmationPending, finalize_requested: finalize }) }); if (!response.ok) { const payload = await response.json().catch(() => null); if (!finalize) setComposer(message); setRetryMessage(message); setStatus("error"); setNotice(conversationErrorMessage(conversationErrorCode(payload))); return; } const payload = await readConversationStream(response, (delta) => { setStatus("streaming"); enqueueReplyDelta(delta); }); flushReply(); const result = parseConversation(payload); if (!result) throw new ConversationStreamError("SKIN_CONVERSATION_INTERNAL_ERROR"); const reply = { id: replyId, role: "assistant" as const, content: result.reply, kind: "reply" as const }; setMessages((current) => { const index = current.findIndex((item) => item.id === replyId); if (index < 0) return [...current, reply]; const next = [...current]; next[index] = reply; return next; }); if (process.env.NODE_ENV === "development") requestAnimationFrame(() => console.info("[skin-conversation]", { stage: "client_timing", transport: "sse", submit_to_complete_ms: Math.round(performance.now() - clientStartedAt), streamed_reply_characters: streamedReply.length })); setProposal(finalize && result.readiness === "ready" ? result : null); setCompletionConfirmationPending(result.completion_available || result.readiness === "confirm" || (!finalize && result.readiness === "ready")); setRetryMessage(""); if (finalize && result.readiness === "ready") { await save(result.proposed_checkin, [...messages, reply]); return; } setStatus("idle"); } catch (error) { flushReply(); if (!finalize) setComposer(message); setRetryMessage(message); setStatus("error"); setNotice(conversationErrorMessage(error instanceof ConversationStreamError ? error.code : "SKIN_CONVERSATION_PROVIDER_FAILURE")); } finally { if (frame !== null) cancelAnimationFrame(frame); sendInFlight.current = false; } }
  async function save(input: SkinCheckinInput, transcript?: ChatMessage[]) { if (status === "saved" || saveInFlight.current === true) return; saveInFlight.current = true; setStatus("saving"); const startedAt = performance.now(); try { const response = await fetch("/api/v1/skin-checkins", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(input) }); const payload = await response.json().catch(() => null); if (!response.ok) throw new SkinCheckinSaveError(readApiErrorCode(payload) ?? "SKIN_CHECKIN_WRITE_FAILED"); const saved = parseCheckin(payload); if (!saved) throw new SkinCheckinSaveError("SKIN_CHECKIN_RESPONSE_INVALID"); commitTranscriptInBackground(transcript); if (process.env.NODE_ENV === "development") console.info("[skin-checkin-finalize]", { stage: "durable_save", duration_ms: Math.round(performance.now() - startedAt) }); append({ id: crypto.randomUUID(), role: "assistant", content: "好，今天这份皮肤记录已经存好了。", kind: "saved" }); setSavedState(saved.daily_state); setProposal(null); setEditor(null); setStatus("saved"); setNotice("今天的皮肤状态已记录。"); setUnsaved(false); sessionStorage.removeItem(key); } catch (error) { setStatus("error"); setNotice(saveErrorMessage(error)); } finally { saveInFlight.current = false; } }
  function restart() { const state = createRestartedConversationState(); setMessages(state.messages); setComposer(state.composer); setProposal(null); setEditor(null); setSavedState(null); setCompletionConfirmationPending(false); setStatus("idle"); setNotice(""); setUnsaved(false); clearConversationSession(sessionStorage, key); }
  async function resetTodayTestRecord() { if (!isDevelopment || resettingTestRecord) return; setResettingTestRecord(true); setNotice(""); try { const response = await fetch("/api/dev/daily-skin/reset-today", { method: "POST" }); if (!response.ok) throw new Error(); restart(); } catch { setNotice("今日测试记录暂时无法重置。"); } finally { setResettingTestRecord(false); } }
  function updateState(update: (value: DailyState) => DailyState) { setUnsaved(true); setEditor((current) => current ? { ...current, daily_state: update(current.daily_state ?? { version: 2, summary: null, concerns: [] }) } : current); }
  const value = editor ?? proposal?.proposed_checkin;
  const summary = buildTodayObservationSummary(savedState);
  const finalizeButtonVisible = canShowFinalizeButton({ messages, hydrated, status });
  const isHomePresentation = presentation === "home";
  const visibleMessages = isHomePresentation && messages.every((message) => message.kind === "opening") ? [] : messages;
  const showHomeWatermark = isHomePresentation && visibleMessages.length === 0 && !value && status !== "saved";
  const busy = status === "sending" || status === "streaming" || status === "saving";
  const composerActions = <>
    <Button className="h-8 px-2 text-xs" nativeButton={false} render={<Link href="/check-in" />} variant="ghost">手动记录</Button>
    <HomeFeedbackAction routines={feedbackRoutines} />
    {finalizeButtonVisible ? <Button className="h-8 px-2 text-xs" disabled={busy} onClick={() => void send(false, true)} type="button" variant="outline">结束并整理今日状态</Button> : null}
  </>;

  return (
    <ChatShell
      actions={<><Button className="h-9 gap-2 px-2 text-xs sm:h-11 sm:px-3 sm:text-sm" onClick={restart} size="lg" type="button" variant="outline">重新开始</Button>{isHomePresentation ? topActions : null}</>}
      composer={status !== "saved" ? <ChatComposer actions={composerActions} disabled={!hydrated || busy || Boolean(proposal)} notice={notice} onChange={(next) => { setComposer(next); setUnsaved(true); }} onSend={() => void send()} placeholder="例如：今天鼻子很油，脸颊有点干。" roomy={presentation === "home"} sendDisabled={!hydrated || !composer.trim() || busy || Boolean(proposal)} value={composer} /> : null}
      description="哪里和平时不一样，或哪里让你不舒服，都可以直接说。"
      eyebrow={!isHomePresentation ? "今日皮肤记录" : undefined}
      title="今天皮肤感觉怎么样？"
    >
      {showHomeWatermark ? <HomeEmptyWatermark /> : null}
      {visibleMessages.map((item, index) => <div key={item.id} className="space-y-2"><ChatBubble message={item} />{item.role === "user" ? <TodayNewChangeIndicators message={item.content} previousUserMessages={messages.slice(0, index).filter((prior) => prior.role === "user").map((prior) => prior.content)} baseline={profile?.long_term_skin_baseline} /> : null}</div>)}
      {status === "sending" || status === "saving" ? <BrandLoading label={status === "saving" ? "正在保存今天的记录…" : "正在整理你刚才说的情况…"} /> : null}
      {value ? <section className="rounded-2xl border bg-muted/30 p-5"><p className="text-sm font-medium text-muted-foreground">确认今日记录</p>{editor ? <DailyStateEditor state={value.daily_state} onChange={updateState} /> : <DailyStateReport state={value.daily_state} />}<div className="mt-5 flex flex-wrap gap-3"><Button disabled={status === "saving"} onClick={() => void save(value)} type="button">{editor ? "确认并记录" : "记录今天状态"}</Button>{editor ? <Button onClick={() => setEditor(null)} type="button" variant="outline">返回聊天</Button> : <Button onClick={() => { setEditor(value); setUnsaved(true); }} type="button" variant="outline">调整</Button>}</div></section> : null}
      {status === "saved" ? <><p className="text-sm font-medium">今天的皮肤状态已经记录</p><TodayObservationSummary items={summary} /><div className="flex flex-wrap gap-3"><Button nativeButton={false} render={<Link href="/today/am" />}>看看今天怎么护理</Button><Button nativeButton={false} render={<Link href={`/check-in?date=${encodeURIComponent(today)}`} />} variant="outline">查看今日记录</Button>{isDevelopment ? <Button disabled={resettingTestRecord} onClick={() => void resetTodayTestRecord()} type="button" variant="outline">{resettingTestRecord ? "重置中…" : "重置今日测试记录"}</Button> : null}</div></> : null}
    </ChatShell>
  );
}
class SkinCheckinSaveError extends Error { constructor(readonly code: string) { super(code); this.name = "SkinCheckinSaveError"; } }
class ConversationStreamError extends Error { constructor(readonly code: ConversationApiErrorCode) { super(code); this.name = "ConversationStreamError"; } }
async function readConversationStream(response: Response, onReplyDelta: (delta: string) => void): Promise<unknown> {
  if (!response.body) throw new ConversationStreamError("SKIN_CONVERSATION_PROVIDER_FAILURE");
  const reader = response.body.getReader(); const decoder = new TextDecoder(); let buffer = ""; let finalPayload: unknown = null;
  while (true) {
    const read = await reader.read();
    if (read.done) break;
    buffer += decoder.decode(read.value, { stream: true });
    let boundary: number;
    while ((boundary = buffer.indexOf("\n\n")) >= 0) {
      const frame = buffer.slice(0, boundary); buffer = buffer.slice(boundary + 2);
      const event = frame.match(/^event:\s*([^\n\r]+)/m)?.[1]?.trim();
      const data = frame.split(/\r?\n/).filter((line) => line.startsWith("data:")).map((line) => line.slice(5).trimStart()).join("\n");
      if (!event || !data) continue;
      let payload: unknown;
      try { payload = JSON.parse(data); } catch { throw new ConversationStreamError("SKIN_CONVERSATION_INTERNAL_ERROR"); }
      if (event === "reply_delta" && typeof payload === "object" && payload !== null && typeof (payload as { delta?: unknown }).delta === "string") { onReplyDelta((payload as { delta: string }).delta); continue; }
      if (event === "final" && typeof payload === "object" && payload !== null && "data" in payload) { finalPayload = payload; continue; }
      if (event === "error") throw new ConversationStreamError(conversationErrorCode(payload) ?? "SKIN_CONVERSATION_INTERNAL_ERROR");
    }
  }
  if (finalPayload === null) throw new ConversationStreamError("SKIN_CONVERSATION_PROVIDER_FAILURE");
  return finalPayload;
}
function commitTranscriptInBackground(transcript?: ChatMessage[]) { if (!transcript?.length) return; void fetch("/api/v1/skin-conversations/memory-commit", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ transcript: transcript.filter((message) => message.kind !== "opening" && message.kind !== "saved").map(({ role, content }) => ({ role, content })) }) }).catch(() => undefined); }
function readApiErrorCode(value: unknown) { return typeof value === "object" && value !== null && "error" in value && typeof value.error === "object" && value.error !== null && "code" in value.error && typeof value.error.code === "string" ? value.error.code : null; }
function saveErrorMessage(error: unknown) { if (!(error instanceof SkinCheckinSaveError)) return "保存请求未完成，请检查网络后重试。"; if (error.code === "VALIDATION_ERROR") return "今日状态数据还不完整，无法保存。请调整后重试。"; if (error.code === "UNAUTHORIZED") return "登录状态已失效，请重新登录后保存。"; if (error.code === "SKIN_CHECKIN_RESPONSE_INVALID") return "记录已提交，但返回的数据格式异常；请到皮肤状态页刷新确认。"; return "保存服务暂时未完成，请稍后重试。"; }
function TodayNewChangeIndicators({ message, baseline, previousUserMessages }: { message: string; baseline: Profile["long_term_skin_baseline"] | undefined; previousUserMessages: string[] }) { const indicators = getTodayNewChangeIndicators(message, baseline, previousUserMessages); return indicators.length ? <div aria-label="今日新变化" className="ml-auto flex max-w-[85%] flex-wrap justify-end gap-2">{indicators.map((item) => <span className="rounded-full border border-warning/35 bg-warning/10 px-3 py-1 text-xs text-foreground" key={item.key}>{item.label}</span>)}</div> : null; }
function TodayObservationSummary({ items }: { items: string[] }) { return <section aria-label="今日观察摘要" className="rounded-2xl border bg-muted/30 p-5"><h2 className="text-lg font-semibold">今日观察摘要</h2>{items.length ? <ul className="mt-3 list-disc space-y-2 pl-5 text-sm leading-6">{items.map((item) => <li key={item}>{item}</li>)}</ul> : <p className="mt-3 text-sm text-muted-foreground">今天已保存已确认的皮肤记录；完整分析会在详情页生成。</p>}</section>; }
function HomeEmptyWatermark() { return <div aria-label="Beauty OS 空状态品牌水印" className="pointer-events-none absolute inset-0 flex items-center justify-center pb-10" role="img"><div className="w-[280px] opacity-[0.1] sm:w-[470px]"><Image alt="" aria-hidden="true" className="h-auto w-full" height={1024} src="/brand/beauty-os-watermark.png" width={1536} /></div></div>; }
const concernLabels = { oiliness: "出油", dryness: "干燥", flaking: "起皮", roughness: "粗糙", redness: "泛红", stinging: "刺痛", itching: "发痒", burning: "灼热", blemishes: "痘痘", small_bumps: "小凸起", blackheads: "黑头", visible_pores: "毛孔明显", uneven_tone: "肤色不均", dullness: "暗沉", post_blemish_marks: "痘印或残留印记" } as const;
const areaLabels = { t_zone: "T 区", forehead: "额头", hairline: "发际线", nose: "鼻子", nose_wings: "鼻翼", cheeks: "脸颊", chin: "下巴", eye_area: "眼周", full_face: "全脸", other: "局部" } as const;

function DailyStateReport({ state }: { state: DailyState | null }) {
  if (!state) return null;

  return <>
    {state.summary ? <p className="mt-3 text-sm leading-6">{state.summary}</p> : null}
    <section className="mt-5 border-t pt-4">
      <p className="text-sm font-medium">今天比较值得留意</p>
      {state.version === 1 && state.details.length ? <ul className="mt-3 grid gap-2 sm:grid-cols-2">{state.details.map((detail, index) => <li className="rounded-lg border bg-background p-3 text-sm" key={`${detail.area}:${detail.finding}:${index}`}><b>{detail.area ? `${detail.area} · ` : ""}{labels[detail.finding]}</b>：{detail.status === "absent" ? "明确没有" : detail.description ?? "已记录"}</li>)}</ul> : null}
      {state.version === 2 && state.concerns.length ? <ul className="mt-3 grid gap-2 sm:grid-cols-2">{state.concerns.map((concern, index) => <li className="rounded-lg border bg-background p-3 text-sm" key={`${concern.kind}:${concern.areas.join(",")}:${index}`}><b>{concern.areas.map((area) => areaLabels[area]).join("、")} · {concernLabels[concern.kind]}</b>：{concern.status === "absent" ? "明确没有" : concern.user_wording.join("；") || "已记录"}</li>)}</ul> : null}
    </section>
    <p className="mt-5 text-xs leading-5 text-muted-foreground">这些会被记进今天的皮肤记录里；如果类似情况之后反复出现，我会帮你整理到“近期变化”里。</p>
  </>;
}

function DailyStateEditor({ state, onChange }: { state: DailyState | null; onChange: (update: (value: DailyState) => DailyState) => void }) { const value = state ?? { version: 2 as const, summary: null, concerns: [] }; if (value.version === 2) return <div className="mt-4 space-y-3"><label className="block text-sm">今日摘要<textarea className="mt-2 min-h-20 w-full rounded border p-2" value={value.summary ?? ""} onChange={(event) => onChange((current) => ({ ...current, summary: event.target.value.trim() || null }))} /></label>{value.concerns.map((concern, index) => <div className="grid gap-2 rounded-lg border bg-background p-3 sm:grid-cols-4" key={index}><select className="h-9 rounded border px-2 text-sm" value={concern.kind} onChange={(event) => onChange((current) => changeConcern(current, index, { kind: event.target.value as typeof concern.kind }))}>{DAILY_STATE_CONCERN_KINDS.map((kind) => <option key={kind} value={kind}>{concernLabels[kind]}</option>)}</select><select className="h-9 rounded border px-2 text-sm" value={concern.areas[0]} onChange={(event) => onChange((current) => changeConcern(current, index, { areas: [event.target.value as typeof concern.areas[number]] }))}>{DAILY_STATE_AREAS.map((area) => <option key={area} value={area}>{areaLabels[area]}</option>)}</select><select className="h-9 rounded border px-2 text-sm" value={concern.status} onChange={(event) => onChange((current) => changeConcern(current, index, { status: event.target.value as "present" | "absent" }))}><option value="present">有</option><option value="absent">明确没有</option></select><input className="h-9 rounded border px-2 text-sm" placeholder="用户描述" value={concern.user_wording.join("；")} onChange={(event) => onChange((current) => changeConcern(current, index, { user_wording: event.target.value.trim() ? [event.target.value.trim()] : [], source: [...new Set([...concern.source, "manual" as const])] }))} /></div>)}<Button onClick={() => onChange(appendConcern)} type="button" variant="outline">添加关注项</Button></div>;
  return <div className="mt-4 space-y-3"><label className="block text-sm">今日摘要<textarea className="mt-2 min-h-20 w-full rounded border p-2" value={value.summary ?? ""} onChange={(event) => onChange((current) => ({ ...current, summary: event.target.value.trim() || null }))} /></label>{value.details.map((detail, index) => <div className="grid gap-2 rounded-lg border bg-background p-3 sm:grid-cols-4" key={index}><input className="h-9 rounded border px-2 text-sm" placeholder="区域，例如额头" value={detail.area ?? ""} onChange={(event) => onChange((current) => changeV1(current, index, { area: event.target.value.trim() || null }))} /><select className="h-9 rounded border px-2 text-sm" value={detail.finding} onChange={(event) => onChange((current) => changeV1(current, index, { finding: event.target.value as DailyStateDetailFinding }))}>{DAILY_STATE_DETAIL_FINDINGS.map((finding) => <option key={finding} value={finding}>{labels[finding]}</option>)}</select><select className="h-9 rounded border px-2 text-sm" value={detail.status} onChange={(event) => onChange((current) => changeV1(current, index, { status: event.target.value as "present" | "absent" }))}><option value="present">有</option><option value="absent">明确没有</option></select><input className="h-9 rounded border px-2 text-sm" placeholder="数量、分布或感受" value={detail.description ?? ""} onChange={(event) => onChange((current) => changeV1(current, index, { description: event.target.value.trim() || null, source: [...new Set([...detail.source, "manual" as const])] }))} /></div>)}</div>; }
function changeV1(state: DailyState, index: number, patch: Partial<Extract<DailyState, { version: 1 }>['details'][number]>): DailyState { return state.version === 1 ? { ...state, details: state.details.map((detail, item) => item === index ? { ...detail, ...patch } : detail) } : state; }
function changeConcern(state: DailyState, index: number, patch: Partial<Extract<DailyState, { version: 2 }>['concerns'][number]>): DailyState { return state.version === 2 ? { ...state, concerns: state.concerns.map((concern, item) => item === index ? { ...concern, ...patch } : concern) } : state; }
function appendConcern(state: DailyState): DailyState { return state.version === 2 ? { ...state, concerns: [...state.concerns, { kind: "uneven_tone", status: "present", areas: ["other"], attributes: {}, user_wording: [], source: ["manual"] }] } : state; }
function parseConversation(value: unknown) { if (typeof value !== "object" || value === null || !("data" in value)) return null; const result = skinConversationResultSchema.safeParse(value.data); return result.success ? result.data : null; }
function parseCheckin(value: unknown) { if (typeof value !== "object" || value === null || !("data" in value)) return null; const result = skinCheckinSchema.safeParse(value.data); return result.success ? result.data : null; }

